name: ai_wrozka
description: Aplikacja do wróżenia z dłoni z wykorzystaniem AI
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^3.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  camera: ^0.10.5+5
  http: ^1.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/sound/
    - assets/data/